Revert "have each validator randomly pick a stability subnet, per spec (#2194)"
This reverts commit 048a67d525cf6185d747353919897b95c0adf3de.

Fails with:
```
Error: unhandled exception: /data/beacon-node-builds/devel-large/repo/beacon_chain/nimbus_beacon_node.nim(442, 12) `node.attestationSubnets.stabilitySubnets.len == 0`  [AssertionError]
```